[package]
name = "grist-image-optimizer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "env"] }
grist-client = { path = "../grist-client" }
tokio = { version = "1", features = ["full"] }
serde_json = "^1.0"
futures = "0.3.31"